/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CentralDeAjudaRouteImport } from './routes/central-de-ajuda'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppComprarRouteImport } from './routes/app.comprar'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppDesempenhoRouteImport } from './routes/app.desempenho'
import { Route as AppEmpresaRouteImport } from './routes/app.empresa'
import { Route as AppFavoritosRouteImport } from './routes/app.favoritos'
import { Route as AppMensagensRouteImport } from './routes/app.mensagens'
import { Route as AppMeusAnunciosRouteImport } from './routes/app.meus-anuncios'
import { Route as AppNegociacoesRouteImport } from './routes/app.negociacoes'
import { Route as AppNotificacoesRouteImport } from './routes/app.notificacoes'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppPropostasRouteImport } from './routes/app.propostas'
import { Route as AppPropostasRecebidasRouteImport } from './routes/app.propostas-recebidas'
import { Route as AppPublicarRouteImport } from './routes/app.publicar'
import { Route as ImplementosSlugRouteImport } from './routes/implementos.$slug'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralDeAjudaRoute = CentralDeAjudaRouteImport.update({
  id: '/central-de-ajuda',
  path: '/central-de-ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppComprarRoute = AppComprarRouteImport.update({
  id: '/comprar',
  path: '/comprar',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppDesempenhoRoute = AppDesempenhoRouteImport.update({
  id: '/desempenho',
  path: '/desempenho',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresaRoute = AppEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritosRoute = AppFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AppRoute,
} as any)
const AppMensagensRoute = AppMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AppRoute,
} as any)
const AppMeusAnunciosRoute = AppMeusAnunciosRouteImport.update({
  id: '/meus-anuncios',
  path: '/meus-anuncios',
  getParentRoute: () => AppRoute,
} as any)
const AppNegociacoesRoute = AppNegociacoesRouteImport.update({
  id: '/negociacoes',
  path: '/negociacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasRoute = AppPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AppRoute,
} as any)
const AppPropostasRecebidasRoute = AppPropostasRecebidasRouteImport.update({
  id: '/propostas-recebidas',
  path: '/propostas-recebidas',
  getParentRoute: () => AppRoute,
} as any)
const AppPublicarRoute = AppPublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => AppRoute,
} as any)
const ImplementosSlugRoute = ImplementosSlugRouteImport.update({
  id: '/implementos/$slug',
  path: '/implementos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/catalogo': typeof CatalogoRoute
  '/central-de-ajuda': typeof CentralDeAjudaRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/entrar': typeof EntrarRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/seguranca': typeof SegurancaRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/app/comprar': typeof AppComprarRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/desempenho': typeof AppDesempenhoRoute
  '/app/empresa': typeof AppEmpresaRoute
  '/app/favoritos': typeof AppFavoritosRoute
  '/app/mensagens': typeof AppMensagensRoute
  '/app/meus-anuncios': typeof AppMeusAnunciosRoute
  '/app/negociacoes': typeof AppNegociacoesRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/propostas': typeof AppPropostasRoute
  '/app/propostas-recebidas': typeof AppPropostasRecebidasRoute
  '/app/publicar': typeof AppPublicarRoute
  '/implementos/$slug': typeof ImplementosSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/catalogo': typeof CatalogoRoute
  '/central-de-ajuda': typeof CentralDeAjudaRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/entrar': typeof EntrarRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/seguranca': typeof SegurancaRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/app/comprar': typeof AppComprarRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/desempenho': typeof AppDesempenhoRoute
  '/app/empresa': typeof AppEmpresaRoute
  '/app/favoritos': typeof AppFavoritosRoute
  '/app/mensagens': typeof AppMensagensRoute
  '/app/meus-anuncios': typeof AppMeusAnunciosRoute
  '/app/negociacoes': typeof AppNegociacoesRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/propostas': typeof AppPropostasRoute
  '/app/propostas-recebidas': typeof AppPropostasRecebidasRoute
  '/app/publicar': typeof AppPublicarRoute
  '/implementos/$slug': typeof ImplementosSlugRoute
  '/app': typeof AppIndexRoute
  '/app/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/catalogo': typeof CatalogoRoute
  '/central-de-ajuda': typeof CentralDeAjudaRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/entrar': typeof EntrarRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/seguranca': typeof SegurancaRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/app/comprar': typeof AppComprarRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/desempenho': typeof AppDesempenhoRoute
  '/app/empresa': typeof AppEmpresaRoute
  '/app/favoritos': typeof AppFavoritosRoute
  '/app/mensagens': typeof AppMensagensRoute
  '/app/meus-anuncios': typeof AppMeusAnunciosRoute
  '/app/negociacoes': typeof AppNegociacoesRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/propostas': typeof AppPropostasRoute
  '/app/propostas-recebidas': typeof AppPropostasRecebidasRoute
  '/app/publicar': typeof AppPublicarRoute
  '/implementos/$slug': typeof ImplementosSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/catalogo'
    | '/central-de-ajuda'
    | '/como-funciona'
    | '/contato'
    | '/entrar'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/seguranca'
    | '/termos-de-uso'
    | '/app/comprar'
    | '/app/configuracoes'
    | '/app/desempenho'
    | '/app/empresa'
    | '/app/favoritos'
    | '/app/mensagens'
    | '/app/meus-anuncios'
    | '/app/negociacoes'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/propostas'
    | '/app/propostas-recebidas'
    | '/app/publicar'
    | '/implementos/$slug'
    | '/app/'
    | '/app/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/catalogo'
    | '/central-de-ajuda'
    | '/como-funciona'
    | '/contato'
    | '/entrar'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/seguranca'
    | '/termos-de-uso'
    | '/app/comprar'
    | '/app/configuracoes'
    | '/app/desempenho'
    | '/app/empresa'
    | '/app/favoritos'
    | '/app/mensagens'
    | '/app/meus-anuncios'
    | '/app/negociacoes'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/propostas'
    | '/app/propostas-recebidas'
    | '/app/publicar'
    | '/implementos/$slug'
    | '/app'
    | '/app/admin'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cadastro'
    | '/catalogo'
    | '/central-de-ajuda'
    | '/como-funciona'
    | '/contato'
    | '/entrar'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/seguranca'
    | '/termos-de-uso'
    | '/app/comprar'
    | '/app/configuracoes'
    | '/app/desempenho'
    | '/app/empresa'
    | '/app/favoritos'
    | '/app/mensagens'
    | '/app/meus-anuncios'
    | '/app/negociacoes'
    | '/app/notificacoes'
    | '/app/perfil'
    | '/app/propostas'
    | '/app/propostas-recebidas'
    | '/app/publicar'
    | '/implementos/$slug'
    | '/app/'
    | '/app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  CatalogoRoute: typeof CatalogoRoute
  CentralDeAjudaRoute: typeof CentralDeAjudaRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContatoRoute: typeof ContatoRoute
  EntrarRoute: typeof EntrarRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SegurancaRoute: typeof SegurancaRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  ImplementosSlugRoute: typeof ImplementosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central-de-ajuda': {
      id: '/central-de-ajuda'
      path: '/central-de-ajuda'
      fullPath: '/central-de-ajuda'
      preLoaderRoute: typeof CentralDeAjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comprar': {
      id: '/app/comprar'
      path: '/comprar'
      fullPath: '/app/comprar'
      preLoaderRoute: typeof AppComprarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/desempenho': {
      id: '/app/desempenho'
      path: '/desempenho'
      fullPath: '/app/desempenho'
      preLoaderRoute: typeof AppDesempenhoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/empresa': {
      id: '/app/empresa'
      path: '/empresa'
      fullPath: '/app/empresa'
      preLoaderRoute: typeof AppEmpresaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/favoritos': {
      id: '/app/favoritos'
      path: '/favoritos'
      fullPath: '/app/favoritos'
      preLoaderRoute: typeof AppFavoritosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mensagens': {
      id: '/app/mensagens'
      path: '/mensagens'
      fullPath: '/app/mensagens'
      preLoaderRoute: typeof AppMensagensRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meus-anuncios': {
      id: '/app/meus-anuncios'
      path: '/meus-anuncios'
      fullPath: '/app/meus-anuncios'
      preLoaderRoute: typeof AppMeusAnunciosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/negociacoes': {
      id: '/app/negociacoes'
      path: '/negociacoes'
      fullPath: '/app/negociacoes'
      preLoaderRoute: typeof AppNegociacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notificacoes': {
      id: '/app/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propostas': {
      id: '/app/propostas'
      path: '/propostas'
      fullPath: '/app/propostas'
      preLoaderRoute: typeof AppPropostasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/propostas-recebidas': {
      id: '/app/propostas-recebidas'
      path: '/propostas-recebidas'
      fullPath: '/app/propostas-recebidas'
      preLoaderRoute: typeof AppPropostasRecebidasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/publicar': {
      id: '/app/publicar'
      path: '/publicar'
      fullPath: '/app/publicar'
      preLoaderRoute: typeof AppPublicarRouteImport
      parentRoute: typeof AppRoute
    }
    '/implementos/$slug': {
      id: '/implementos/$slug'
      path: '/implementos/$slug'
      fullPath: '/implementos/$slug'
      preLoaderRoute: typeof ImplementosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppComprarRoute: typeof AppComprarRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDesempenhoRoute: typeof AppDesempenhoRoute
  AppEmpresaRoute: typeof AppEmpresaRoute
  AppFavoritosRoute: typeof AppFavoritosRoute
  AppMensagensRoute: typeof AppMensagensRoute
  AppMeusAnunciosRoute: typeof AppMeusAnunciosRoute
  AppNegociacoesRoute: typeof AppNegociacoesRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPropostasRoute: typeof AppPropostasRoute
  AppPropostasRecebidasRoute: typeof AppPropostasRecebidasRoute
  AppPublicarRoute: typeof AppPublicarRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppComprarRoute: AppComprarRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDesempenhoRoute: AppDesempenhoRoute,
  AppEmpresaRoute: AppEmpresaRoute,
  AppFavoritosRoute: AppFavoritosRoute,
  AppMensagensRoute: AppMensagensRoute,
  AppMeusAnunciosRoute: AppMeusAnunciosRoute,
  AppNegociacoesRoute: AppNegociacoesRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPropostasRoute: AppPropostasRoute,
  AppPropostasRecebidasRoute: AppPropostasRecebidasRoute,
  AppPublicarRoute: AppPublicarRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  CatalogoRoute: CatalogoRoute,
  CentralDeAjudaRoute: CentralDeAjudaRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContatoRoute: ContatoRoute,
  EntrarRoute: EntrarRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SegurancaRoute: SegurancaRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  ImplementosSlugRoute: ImplementosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
